import type * as monaco from 'monaco-editor'

export const PAGE_BUILDER_CODE_EDITOR_THEME: monaco.editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6A737D', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'CF222E' },
    { token: 'string', foreground: '0A3069' },
    { token: 'number', foreground: '116329' },
    { token: 'regexp', foreground: '8250DF' },
    { token: 'type', foreground: '953800' },
    { token: 'class', foreground: '953800' },
    { token: 'namespace', foreground: '953800' },
    { token: 'function', foreground: '6639BA' },
    { token: 'identifier.function', foreground: '6639BA' },
    { token: 'variable', foreground: '24292F' },
    { token: 'delimiter', foreground: '57606A' },
    { token: 'delimiter.bracket', foreground: '57606A' },
    { token: 'operator', foreground: '57606A' },

    { token: 'tag', foreground: '116329' },
    { token: 'tag.html', foreground: '116329' },
    { token: 'metatag.html', foreground: 'CF222E' },
    { token: 'delimiter.html', foreground: '57606A' },
    { token: 'delimiter.angle.html', foreground: '57606A' },
    { token: 'attribute.name', foreground: '0550AE' },
    { token: 'attribute.name.html', foreground: '0550AE' },
    { token: 'attribute.value', foreground: '0A3069' },
    { token: 'attribute.value.html', foreground: '0A3069' },

    { token: 'tag.css', foreground: '116329' },
    { token: 'attribute.name.css', foreground: '0550AE' },
    { token: 'attribute.value.css', foreground: '953800' },
    { token: 'keyword.css', foreground: 'CF222E' },
    { token: 'number.css', foreground: '116329' },
    { token: 'string.css', foreground: '0A3069' },
    { token: 'type.css', foreground: '953800' },
    { token: 'operator.css', foreground: '57606A' },

    { token: 'keyword.js', foreground: 'CF222E' },
    { token: 'keyword.ts', foreground: 'CF222E' },
    { token: 'string.js', foreground: '0A3069' },
    { token: 'string.ts', foreground: '0A3069' },
    { token: 'number.js', foreground: '116329' },
    { token: 'number.ts', foreground: '116329' },
    { token: 'regexp.js', foreground: '8250DF' },
    { token: 'regexp.ts', foreground: '8250DF' },
    { token: 'identifier.function.js', foreground: '6639BA' },
    { token: 'identifier.function.ts', foreground: '6639BA' },
    { token: 'type.identifier.ts', foreground: '953800' },
  ],
  colors: {
    'editor.background': '#FFFFFF',
    'editor.foreground': '#24292F',
    'editorCursor.foreground': '#0969DA',
    'editorLineNumber.foreground': '#8C959F',
    'editorLineNumber.activeForeground': '#24292F',
    'editor.selectionBackground': '#BBDFFF',
    'editor.inactiveSelectionBackground': '#DDF4FF',
    'editor.lineHighlightBackground': '#F6F8FA',
    'editorWhitespace.foreground': '#D0D7DE',
    'editorIndentGuide.background': '#D8DEE4',
    'editorIndentGuide.activeBackground': '#8C959F',
    'editorBracketMatch.background': '#DDF4FF',
    'editorBracketMatch.border': '#54AEFF',
    'editorBracketHighlight.foreground1': '#0969DA',
    'editorBracketHighlight.foreground2': '#116329',
    'editorBracketHighlight.foreground3': '#953800',
    'editorBracketHighlight.foreground4': '#8250DF',
    'editorBracketHighlight.foreground5': '#CF222E',
    'editorBracketHighlight.foreground6': '#0550AE',
    'editorOverviewRuler.border': '#D0D7DE',
  },
}

export interface PageBuilderCodeEditorOptionsInput {
  readOnly: boolean
  minimapEnabled: boolean
}

export function createPageBuilderCodeEditorOptions({
  readOnly,
  minimapEnabled,
}: PageBuilderCodeEditorOptionsInput): monaco.editor.IStandaloneEditorConstructionOptions {
  return {
    readOnly,
    minimap: { enabled: minimapEnabled },
    fontFamily: '"JetBrains Mono", "Fira Code", "SFMono-Regular", Consolas, "Liberation Mono", Menlo, monospace',
    fontLigatures: true,
    fontSize: 13,
    lineHeight: 20,
    renderWhitespace: 'selection',
    scrollBeyondLastLine: false,
    automaticLayout: true,
    wordWrap: 'on',
    tabSize: 2,
    padding: { top: 8 },
    bracketPairColorization: { enabled: true },
    guides: { bracketPairs: true, indentation: true },
    smoothScrolling: true,
    cursorBlinking: 'smooth',
    cursorSmoothCaretAnimation: 'on',
    stickyScroll: { enabled: true },
    linkedEditing: true,
    renderLineHighlight: 'all',
    matchBrackets: 'always',
  }
}
