import { describe, expect, test } from 'bun:test'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

function readRepoFile(relativePath: string): string {
  return readFileSync(fileURLToPath(new URL(relativePath, import.meta.url)), 'utf-8')
}

function readComposeServiceBlock(compose: string, serviceName: string): string {
  const match = compose.match(new RegExp(`\\n  ${serviceName}:\\n[\\s\\S]*?(?=\\n  \\w|\\n?$)`))
  return match?.[0] ?? ''
}

describe('page-builder docker assets', () => {
  test('compose defines a default internal playwright sidecar and docker runtime defaults', () => {
    const compose = readRepoFile('../../../../../build/docker-compose.yml')

    expect(compose).toContain('\n  playwright:\n')
    expect(compose).toContain('image: mcr.microsoft.com/playwright:v1.57.0-jammy')
    expect(compose).toContain('AI_PAGE_BUILDER_RUNTIME_ENV: docker')
    expect(compose).toContain('ANTHROPIC_API_KEY: ${AI_PAGE_BUILDER_ANTHROPIC_API_KEY:?Set AI_PAGE_BUILDER_ANTHROPIC_API_KEY')
    expect(compose).toContain('ANTHROPIC_BASE_URL: ${AI_PAGE_BUILDER_ANTHROPIC_BASE_URL:-}')
    expect(compose).not.toContain('ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY')
    expect(compose).not.toContain('ANTHROPIC_BASE_URL: ${ANTHROPIC_BASE_URL')
    expect(compose).toContain('AI_PAGE_BUILDER_PLAYWRIGHT_MCP_URL: ${AI_PAGE_BUILDER_PLAYWRIGHT_MCP_URL:-http://playwright:8931/mcp}')
    expect(compose).toContain('AI_PAGE_BUILDER_INTERNAL_APP_ORIGIN: ${AI_PAGE_BUILDER_INTERNAL_APP_ORIGIN:-http://server:8888}')
    expect(compose).toContain("PLAYWRIGHT_EXECUTABLE_PATH=\"$(find /ms-playwright/chromium-* \\( -path '*chrome-linux/chrome' -o -path '*chrome-linux64/chrome' \\) | head -1)\"")
    expect(compose).toContain('if [ -z "$$PLAYWRIGHT_EXECUTABLE_PATH" ]; then')
    expect(compose).toContain('--executable-path "$$PLAYWRIGHT_EXECUTABLE_PATH"')
    expect(compose).not.toContain('\n    profiles:\n      - playwright\n')
    expect(compose).toMatch(/  playwright:\n(?: {4}.*\n)+?    volumes:\n      - type: bind\n        source: \$\{AI_PAGE_BUILDER_HOST_DATA_DIR:-\$\{HOME:\?Set HOME in your shell\}\/\.ai-page-builder\}\n        target: \/home\/bun\/\.ai-page-builder\n/s)
    expect(compose).toContain('\n    expose:\n      - "8931"\n')
    expect(compose).toContain('\n    ports:\n      - "${PAGE_BUILDER_PORT:-3333}:3333"\n')
    expect(compose).not.toContain('\n    depends_on:\n      - playwright\n')
  })

  test('env example documents default playwright runtime overrides', () => {
    const envExample = readRepoFile('../../../../../build/.env.standalone.example')

    expect(envExample).toContain('AI_PAGE_BUILDER_ANTHROPIC_API_KEY=')
    expect(envExample).toContain('AI_PAGE_BUILDER_ANTHROPIC_BASE_URL=')
    expect(envExample).not.toMatch(/^ANTHROPIC_API_KEY=/m)
    expect(envExample).not.toMatch(/^ANTHROPIC_BASE_URL=/m)
    expect(envExample).toContain('AI_PAGE_BUILDER_PLAYWRIGHT_MCP_URL=')
    expect(envExample).toContain('AI_PAGE_BUILDER_INTERNAL_APP_ORIGIN=')
    expect(envExample).toContain('Playwright MCP sidecar')
    expect(envExample).toContain('不要配置为浏览器 public origin')
    expect(envExample).toContain('AI_PAGE_BUILDER_PUBLIC_ORIGIN=')
    expect(envExample).toContain('AI_PAGE_BUILDER_HANDOFF_TTL_MS=')
    expect(envExample).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_TTL_MS=')
    expect(envExample).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS=')
    expect(envExample).toContain('AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS=0')
    expect(envExample).toContain('AI_PAGE_BUILDER_HOST_DATA_DIR=')
  })

  test('docker assets explain CMS runtime store persistence inputs', () => {
    const cmsEnvExample = readRepoFile('../../../../../build/.env.cms.example')

    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS=')
    expect(cmsEnvExample).toContain('integrations/cms/runtime')
    expect(cmsEnvExample).toContain('单 server 实例')
    expect(cmsEnvExample).toContain('默认文件 runtime store 只支持单 server 实例语义')
  })

  test('docker assets expose page-builder public base path as runtime configuration', () => {
    const standaloneEnvExample = readRepoFile('../../../../../build/.env.standalone.example')
    const cmsEnvExample = readRepoFile('../../../../../build/.env.cms.example')
    const dockerfile = readRepoFile('../../../../../build/Dockerfile.page-builder-web')
    const compose = readRepoFile('../../../../../build/docker-compose.yml')
    const serverBlock = readComposeServiceBlock(compose, 'server')
    const webBlock = readComposeServiceBlock(compose, 'web')

    expect(standaloneEnvExample).toContain('AI_PAGE_BUILDER_BASE_PATH=')
    expect(standaloneEnvExample).toContain('AI_PAGE_BUILDER_HOST_DATA_DIR=')
    expect(standaloneEnvExample).toContain('子路径部署')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_BASE_PATH=/pagebuilder')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_ANTHROPIC_API_KEY=')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_ANTHROPIC_BASE_URL=')
    expect(cmsEnvExample).not.toMatch(/^ANTHROPIC_API_KEY=/m)
    expect(cmsEnvExample).not.toMatch(/^ANTHROPIC_BASE_URL=/m)
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_PUBLIC_ORIGIN=')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_HANDOFF_TTL_MS=')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_TTL_MS=')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS=')
    expect(cmsEnvExample).toContain('文件 runtime store')
    expect(cmsEnvExample).toContain('AI_PAGE_BUILDER_HOST_DATA_DIR=')

    expect(dockerfile).not.toContain('ARG AI_PAGE_BUILDER_BASE_PATH=')
    expect(dockerfile).not.toContain('AI_PAGE_BUILDER_BASE_PATH="$AI_PAGE_BUILDER_BASE_PATH" bun run --filter')
    expect(dockerfile).toContain("RUN bun run --filter='@ai-page-builder/page-builder' build")
    expect(dockerfile).toContain('COPY --from=deps /app/node_modules ./node_modules')
    expect(dockerfile).toContain('COPY --from=build /app/packages/shared ./packages/shared')

    expect(compose).toContain('AI_PAGE_BUILDER_BASE_PATH: ${AI_PAGE_BUILDER_BASE_PATH:-}')
    expect(compose).toContain('AI_PAGE_BUILDER_PUBLIC_ORIGIN: ${AI_PAGE_BUILDER_PUBLIC_ORIGIN:-}')
    expect(compose).toContain('AI_PAGE_BUILDER_HANDOFF_TTL_MS: ${AI_PAGE_BUILDER_HANDOFF_TTL_MS:-}')
    expect(compose).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_TTL_MS: ${AI_PAGE_BUILDER_ACCESS_SESSION_TTL_MS:-}')
    expect(compose).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS: ${AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS:-}')
    expect(compose).toContain('AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS: ${AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS:-0}')
    expect(compose).toContain('source: ${AI_PAGE_BUILDER_HOST_DATA_DIR:-${HOME:?Set HOME in your shell}/.ai-page-builder}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_BASE_PATH: ${AI_PAGE_BUILDER_BASE_PATH:-}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_PUBLIC_ORIGIN: ${AI_PAGE_BUILDER_PUBLIC_ORIGIN:-}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_HANDOFF_TTL_MS: ${AI_PAGE_BUILDER_HANDOFF_TTL_MS:-}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_TTL_MS: ${AI_PAGE_BUILDER_ACCESS_SESSION_TTL_MS:-}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS: ${AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS:-}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS: ${AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS:-0}')
    expect(webBlock).toContain('AI_PAGE_BUILDER_BASE_PATH: ${AI_PAGE_BUILDER_BASE_PATH:-}')
    expect(webBlock).not.toContain('args:')
    expect(compose).not.toContain('/pagebuilder/api')
  })

  test('cms verification compose keeps mock and nginx out of the default stack', () => {
    const defaultCompose = readRepoFile('../../../../../build/docker-compose.yml')
    const verifyCompose = readRepoFile('../../../../../build/docker-compose.cms-verify.yml')
    const nginxConfig = readRepoFile('../../../../../build/nginx/cms-verify.conf')
    const cmsMock = readRepoFile('../../../../../build/cms-mock/server.ts')
    const smokeTest = readRepoFile('../../../../../build/cms-verify/smoke-test.ts')

    expect(defaultCompose).not.toContain('cms-mock:')
    expect(defaultCompose).not.toContain('cms-verify-nginx')
    expect(verifyCompose).toContain('name: ai-page-builder-cms-verify')
    expect(verifyCompose).toContain('container_name: cms-verify-server')
    expect(verifyCompose).toContain('container_name: cms-verify-web')
    expect(verifyCompose).toContain('container_name: cms-verify-playwright')
    expect(verifyCompose).toContain('container_name: cms-verify-cms-mock')
    expect(verifyCompose).toContain('container_name: cms-verify-nginx')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_INTEGRATION_MODE: cms')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_ANTHROPIC_API_KEY: ${AI_PAGE_BUILDER_ANTHROPIC_API_KEY:-cms-verify-dummy-key}')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_ANTHROPIC_BASE_URL: ${AI_PAGE_BUILDER_ANTHROPIC_BASE_URL:-}')
    expect(verifyCompose).toContain('ANTHROPIC_API_KEY: ${AI_PAGE_BUILDER_ANTHROPIC_API_KEY:-cms-verify-dummy-key}')
    expect(verifyCompose).toContain('ANTHROPIC_BASE_URL: ${AI_PAGE_BUILDER_ANTHROPIC_BASE_URL:-}')
    expect(verifyCompose).not.toContain('ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY')
    expect(verifyCompose).not.toContain('ANTHROPIC_BASE_URL: ${ANTHROPIC_BASE_URL')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_CMS_BASE_URL: http://nginx:8080/manager')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_BASE_PATH: /pagebuilder')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS: ${AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS:-3600000}')
    expect(verifyCompose).toContain('AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS: ${AI_PAGE_BUILDER_SYNC_EXPORT_TIMEOUT_MS:-30000}')
    expect(verifyCompose).toContain('source: ./.cms-verify-data')
    expect(verifyCompose).toContain('source: ./cms-mock')
    expect(verifyCompose).toContain('source: ./nginx/cms-verify.conf')

    expect(nginxConfig).toContain('location /pagebuilder/')
    expect(nginxConfig).toContain('proxy_pass http://web:3333;')
    expect(nginxConfig).toContain('proxy_set_header Authorization $http_authorization;')
    expect(nginxConfig).toContain('proxy_set_header X-CMS-Cookie $http_x_cms_cookie;')
    expect(nginxConfig).toContain('proxy_set_header X-Forwarded-Proto $scheme;')
    expect(nginxConfig).toContain('proxy_set_header X-Forwarded-Host $http_host;')
    expect(nginxConfig).toContain('location /manager/')
    expect(cmsMock).toContain("url.pathname === '/manager/ui/login'")
    expect(cmsMock).toContain("url.pathname === '/cms-mock/'")
    expect(smokeTest).toContain("url('/api/integrations/cms/projects')")
    expect(smokeTest).toContain('workspace-scoped CMS asset proxy')
    expect(smokeTest).not.toContain('/api/page-builder/cms/assets?url=')
  })

  test('release compose uses remote images without local builds', () => {
    const releaseCompose = readRepoFile('../../../../../build/docker-compose.release.yml')
    const serverBlock = readComposeServiceBlock(releaseCompose, 'server')
    const webBlock = readComposeServiceBlock(releaseCompose, 'web')
    const playwrightBlock = readComposeServiceBlock(releaseCompose, 'playwright')

    expect(releaseCompose).toContain('name: ai-page-builder')
    expect(releaseCompose).not.toContain('\n    build:\n')
    expect(releaseCompose).not.toContain('dockerfile:')
    expect(serverBlock).toContain('image: ccr.ccs.tencentyun.com/ai-page-builder/page-builder-server:${PAGE_BUILDER_IMAGE_TAG:-latest}')
    expect(webBlock).toContain('image: ccr.ccs.tencentyun.com/ai-page-builder/page-builder-web:${PAGE_BUILDER_IMAGE_TAG:-latest}')
    expect(playwrightBlock).toContain('image: ${AI_PAGE_BUILDER_PLAYWRIGHT_IMAGE:-mcr.microsoft.com/playwright:v1.57.0-jammy}')
    expect(serverBlock).toContain('restart: unless-stopped')
    expect(webBlock).toContain('restart: unless-stopped')
    expect(playwrightBlock).toContain('restart: unless-stopped')
    expect(serverBlock).toContain('ANTHROPIC_API_KEY: ${AI_PAGE_BUILDER_ANTHROPIC_API_KEY:?Set AI_PAGE_BUILDER_ANTHROPIC_API_KEY}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS: ${AI_PAGE_BUILDER_ACCESS_SESSION_RENEW_THRESHOLD_MS:-}')
    expect(serverBlock).toContain('AI_PAGE_BUILDER_PLAYWRIGHT_MCP_URL: ${AI_PAGE_BUILDER_PLAYWRIGHT_MCP_URL:-http://playwright:8931/mcp}')
    expect(serverBlock).toContain('source: ${AI_PAGE_BUILDER_HOST_DATA_DIR:-${HOME:?Set HOME in your shell}/.ai-page-builder}')
    expect(webBlock).toContain('AI_PAGE_BUILDER_SERVER_ORIGIN: http://server:8888')
    expect(webBlock).toContain('AI_PAGE_BUILDER_BASE_PATH: ${AI_PAGE_BUILDER_BASE_PATH:-}')
    expect(webBlock).toContain('${PAGE_BUILDER_PORT:-3333}:3333')
    expect(playwrightBlock).toContain('--host 0.0.0.0 --port 8931 --headless')
  })
})
